import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from 'react';
import { Plus, Search, Database, Server, Cloud, CheckCircle2, AlertCircle, MoreVertical, RefreshCw, Plug2 } from 'lucide-react';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import { fetchConnectors, openCreateConnection } from '@/store/slices/connectionsSlice';
export function ConnectionsManager() {
    const dispatch = useAppDispatch();
    const connections = useAppSelector(s => s.connections.connectors);
    const loading = useAppSelector(s => s.connections.isLoading);
    const [searchQuery, setSearchQuery] = useState('');
    useEffect(() => {
        dispatch(fetchConnectors());
    }, [dispatch]);
    const getIcon = (type) => {
        const t = type.toLowerCase();
        if (t.includes('postgres') || t.includes('sql'))
            return _jsx(Database, { size: 18 });
        if (t.includes('s3') || t.includes('cloud'))
            return _jsx(Cloud, { size: 18 });
        return _jsx(Server, { size: 18 });
    };
    const filteredConnections = connections.filter(c => c.connectorDisplayName.toLowerCase().includes(searchQuery.toLowerCase()) ||
        c.connectorTypeCode.toLowerCase().includes(searchQuery.toLowerCase()));
    return (_jsxs("div", { className: "max-w-6xl mx-auto", children: [_jsxs("div", { className: "flex items-center justify-between mb-8", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-black text-neutral-900 tracking-tight", children: "Connections" }), _jsx("p", { className: "text-sm text-neutral-500 font-medium", children: "Manage your data sources and destinations" })] }), _jsxs("button", { onClick: () => dispatch(openCreateConnection()), className: "flex items-center gap-2 px-5 py-2.5 bg-brand-500 hover:bg-brand-600 text-white rounded-xl font-bold text-sm shadow-lg shadow-brand-100 transition-all active:scale-[0.98]", children: [_jsx(Plus, { size: 18 }), _jsx("span", { children: "New Connection" })] })] }), _jsxs("div", { className: "bg-white rounded-2xl shadow-sm border border-neutral-200 overflow-hidden", children: [_jsxs("div", { className: "p-4 border-b border-neutral-100 bg-neutral-50/50 flex items-center gap-4", children: [_jsxs("div", { className: "relative flex-1 max-w-md", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 text-neutral-400", size: 16 }), _jsx("input", { type: "text", placeholder: "Search connections...", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), className: "w-full pl-10 pr-4 py-2 bg-white border border-neutral-200 rounded-xl text-sm focus:ring-2 focus:ring-brand-500/10 focus:border-brand-500 outline-none transition-all" })] }), _jsx("button", { onClick: () => dispatch(fetchConnectors()), className: "p-2 hover:bg-neutral-200 rounded-lg text-neutral-500 transition-colors", title: "Refresh", children: _jsx(RefreshCw, { size: 18, className: loading ? 'animate-spin' : '' }) })] }), loading ? (_jsxs("div", { className: "p-20 flex flex-col items-center justify-center gap-4", children: [_jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-2 border-brand-500 border-t-transparent" }), _jsx("p", { className: "text-sm text-neutral-500 font-medium italic", children: "Loading connections..." })] })) : filteredConnections.length === 0 ? (_jsxs("div", { className: "p-20 flex flex-col items-center justify-center text-center", children: [_jsx("div", { className: "w-16 h-16 bg-neutral-100 rounded-2xl flex items-center justify-center mb-4", children: _jsx(Plug2, { className: "w-8 h-8 text-neutral-300" }) }), _jsx("h3", { className: "text-base font-bold text-neutral-900", children: "No connections found" }), _jsx("p", { className: "text-sm text-neutral-500 mt-1 max-w-xs", children: searchQuery ? `No results for "${searchQuery}"` : "Get started by adding your first data connection." }), !searchQuery && (_jsx("button", { className: "mt-6 text-brand-600 font-bold text-sm hover:underline", children: "Create new connection" }))] })) : (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4 lg:p-6", children: filteredConnections.map(conn => {
                            const isActive = conn.healthStatusCode === 'HEALTHY';
                            const isError = conn.healthStatusCode === 'UNHEALTHY' || conn.healthStatusCode === 'ERROR';
                            return (_jsxs("div", { className: "group border border-neutral-200 rounded-2xl p-5 hover:border-brand-500 hover:shadow-lg hover:shadow-brand-50 transition-all cursor-pointer bg-white relative overflow-hidden", children: [_jsx("div", { className: `absolute top-0 left-0 right-0 h-1 ${isActive ? 'bg-success-500' :
                                            isError ? 'bg-danger-500' : 'bg-brand-400'}` }), _jsxs("div", { className: "flex items-start justify-between mb-4", children: [_jsx("div", { className: `w-12 h-12 bg-neutral-100 rounded-xl flex items-center justify-center text-neutral-600 group-hover:bg-brand-50 group-hover:text-brand-600 transition-colors`, children: getIcon(conn.connectorTypeCode) }), _jsx("button", { className: "p-1 px-1.5 hover:bg-neutral-100 rounded-lg text-neutral-400 transition-colors", children: _jsx(MoreVertical, { size: 16 }) })] }), _jsxs("div", { className: "mb-4", children: [_jsx("h3", { className: "font-bold text-neutral-900 group-hover:text-brand-700 transition-colors", children: conn.connectorDisplayName }), _jsx("p", { className: "text-xs text-neutral-500 font-medium uppercase tracking-wider mt-0.5", children: conn.connectorTypeCode })] }), _jsxs("div", { className: "flex items-center justify-between pt-4 border-t border-neutral-100", children: [_jsxs("div", { className: "flex items-center gap-1.5", children: [isActive ? (_jsx(CheckCircle2, { className: "text-success-500", size: 14 })) : isError ? (_jsx(AlertCircle, { className: "text-danger-500", size: 14 })) : (_jsx(RefreshCw, { className: "text-brand-500", size: 14 })), _jsx("span", { className: `text-[11px] font-bold uppercase tracking-tight ${isActive ? 'text-success-700' : isError ? 'text-danger-700' : 'text-brand-700'}`, children: conn.healthStatusCode || 'UNKNOWN' })] }), _jsx("span", { className: "text-[10px] text-neutral-400 font-medium italic", children: conn.updatedDtm ? new Date(conn.updatedDtm).toLocaleDateString() : 'Never tested' })] })] }, conn.connectorId));
                        }) }))] })] }));
}
